# Generated by Django 5.1.6 on 2025-03-10 07:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0002_recipe_author_recipe_created_on_recipe_updated_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="created_on",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
    ]
