# Generated by Django 5.1.6 on 2025-03-24 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0004_alter_recipe_author_alter_recipe_created_on"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
